"""Static registry of every rule mdgoat knows, for docs and `mdgoat rules`."""

from __future__ import annotations

from .models import (
    CATEGORY_ARTIFACT,
    CATEGORY_EFFICIENCY,
    CATEGORY_SECURITY,
    CATEGORY_STRUCTURE,
    Severity,
)

# (rule_id, name, category, worst_severity, fixable, description)
RULES = [
    ("SEC001", "invisible-characters", CATEGORY_SECURITY, Severity.HIGH, True,
     "Zero-width and other invisible Unicode characters."),
    ("SEC002", "unicode-tag-smuggling", CATEGORY_SECURITY, Severity.CRITICAL, True,
     "Unicode tag-block sequences (ASCII smuggling); payload is decoded and shown."),
    ("SEC003", "bidi-controls", CATEGORY_SECURITY, Severity.HIGH, True,
     "Bidirectional override/isolate characters ('Trojan Source')."),
    ("SEC004", "hidden-instructions-in-comment", CATEGORY_SECURITY, Severity.CRITICAL, True,
     "HTML comments containing instruction-like text."),
    ("SEC005", "html-comment", CATEGORY_SECURITY, Severity.LOW, True,
     "Any HTML comment: invisible when rendered, visible to the LLM."),
    ("SEC006", "hidden-html-element", CATEGORY_SECURITY, Severity.CRITICAL, False,
     "Elements styled display:none / visibility:hidden / font-size:0 / hidden."),
    ("SEC007", "instructions-in-alt-text", CATEGORY_SECURITY, Severity.HIGH, False,
     "Instruction-like text in image alt text or link titles."),
    ("SEC008", "image-exfiltration-url", CATEGORY_SECURITY, Severity.HIGH, False,
     "Image URLs pointing at beacon services or carrying long dynamic queries."),
    ("SEC009", "mixed-script-homoglyphs", CATEGORY_SECURITY, Severity.HIGH, False,
     "Words mixing Latin with Cyrillic/Greek lookalike letters."),
    ("ART001", "mojibake", CATEGORY_ARTIFACT, Severity.MEDIUM, True,
     "UTF-8 text that was decoded as Latin-1/cp1252 (e.g. curly quotes gone wrong)."),
    ("ART002", "ligatures", CATEGORY_ARTIFACT, Severity.LOW, True,
     "Typographic ligatures left behind by PDF extraction or OCR."),
    ("ART003", "non-standard-spaces", CATEGORY_ARTIFACT, Severity.LOW, True,
     "Non-breaking and typographic spaces that tokenize differently."),
    ("ART004", "control-characters", CATEGORY_ARTIFACT, Severity.HIGH, True,
     "C0/C1 control characters (form feeds, stray bytes)."),
    ("ART005", "hyphenation-breaks", CATEGORY_ARTIFACT, Severity.LOW, True,
     "Words split across lines by print-layout hyphenation."),
    ("ART006", "replacement-characters", CATEGORY_ARTIFACT, Severity.MEDIUM, False,
     "U+FFFD characters marking unrecoverable data loss."),
    ("ART007", "repeated-boilerplate", CATEGORY_ARTIFACT, Severity.MEDIUM, False,
     "The same line repeated 3+ times (page headers/footers)."),
    ("ART008", "orphaned-page-numbers", CATEGORY_ARTIFACT, Severity.LOW, False,
     "Stranded page-number lines from the source document."),
    ("ART009", "html-residue", CATEGORY_ARTIFACT, Severity.MEDIUM, True,
     "HTML entities and structural tags that should have become markdown."),
    ("STR001", "broken-table", CATEGORY_STRUCTURE, Severity.MEDIUM, False,
     "Table rows whose column count differs from the header."),
    ("STR002", "unclosed-code-fence", CATEGORY_STRUCTURE, Severity.HIGH, False,
     "A code fence that never closes, swallowing the rest of the document."),
    ("STR003", "heading-level-jump", CATEGORY_STRUCTURE, Severity.LOW, False,
     "Heading levels that skip (## straight to ####)."),
    ("STR004", "empty-links", CATEGORY_STRUCTURE, Severity.LOW, False,
     "Links or images whose target was lost in conversion."),
    ("STR005", "headingless-document", CATEGORY_STRUCTURE, Severity.LOW, False,
     "A long document with no headings at all."),
    ("EFF001", "trailing-whitespace", CATEGORY_EFFICIENCY, Severity.INFO, True,
     "Trailing spaces and tabs."),
    ("EFF002", "excessive-blank-lines", CATEGORY_EFFICIENCY, Severity.LOW, True,
     "Runs of 2+ consecutive blank lines."),
    ("EFF003", "duplicate-blocks", CATEGORY_EFFICIENCY, Severity.LOW, False,
     "Identical paragraphs appearing more than once."),
    ("EFF004", "typographic-punctuation", CATEGORY_EFFICIENCY, Severity.INFO, True,
     "Curly quotes, em-dashes, and ellipses normalizable to ASCII."),
]
